[profile.release]
debug = true
lto = true
rpath = false
incremental = true
opt-level = 3
codegen-units = 6

[workspace]

members = [
	"types",
	"dwconsts",
	"integral",
	"fifo",
	"vector3",
 	"lapack_sys"
]

